name: Update Trailhead Stats

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: nabondance/trailhead-stats@v2
        with:
          trailhead-username: 'premkr'
          display-type: 'card'
          showSkill: 'hidden'
          showCertification: 'detail'
          showBadge: 'hidden'
          showSuperBadge: 'hidden'
          showEventBadge: 'hidden'
          showStamp: 'hidden'
          showCertificationLatest: 'hidden'
          showBadgeLatest: 'hidden'
          showSuperBadgeLatest: 'hidden'
          showEventBadgeLatest: 'hidden'
          showStampLatest: 'hidden'
