name: Update Trailhead Stats Manually

on:
  workflow_dispatch: # Allows manual trigger

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Fetch Trailhead Stats
        uses: nabondance/trailhead-stats@v2
        with:
          trailhead-username: 'premkr'
          display-type: 'card'
          show-skill: 'hidden'
          show-certification: 'detail'
          show-badge: 'hidden'
          show-superbadge: 'hidden'
          show-event-badge: 'hidden'
          show-stamp: 'hidden'
          show-certification-latest: 'hidden'
          show-badge-latest: 'hidden'
          show-superbadge-latest: 'hidden'
          show-event-badge-latest: 'hidden'
          show-stamp-latest: 'hidden'
